services:
  - type: web

    name: cms-backend

    env: node

    plan: free

    buildCommand: npm install

    startCommand: npm run dev

    branch: main # Adjust if your default branch is different

    region: singapore # Change to your preferred Render region

    autoDeploy: true

    envVars:
      - key: NODE_ENV

        value: production

      - key: MONGO

        value: "mongodb+srv://deepakgupta:mongodbpaasword@cluster0.xnwuo.mongodb.net/"

      - key: PORT

        value: 4000 # Ensure this matches the port your app listens on